version: 2
registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: /backend
    target-branch: integration
    registries:
      - github-npm
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      vitest:
        patterns:
          - vitest
          - "@vitest/*"
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    target-branch: integration
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      vitest:
        patterns:
          - vitest
          - "@vitest/*"
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: integration
    schedule:
      interval: monthly
